### ISSUE TITLE
Can I print custom ZPL file?

### ISSUE THREAD

**Issue by artem-galas** [bbulpett/zebra-zpl#18]
I have a question about your gem.
Can I have print custom ZPL file?
For example, I build my own template using https://github.com/rjocoleman/labelary and I wont send this template to printer.

Thanks for advise!

**Comment by bbulpett** [comment]
Yes, you absolutely can create custom ZPL labels and send them directly to your Zebrå label printer.

**Comment by LagTag** [comment]
My most recent PR #41 might cover this. I believe @artem-galas already had a zpl string/file they built with Labelary and just wanted to print it.
