### ISSUE TITLE
Error While installing

### ISSUE THREAD

**Issue by gmout** [bbulpett/zebra-zpl#19]
Tested on Windows 10 & Centos 7

Error gem install zebra-zpl
-----------------------------------
$ gem install zebra-zpl
Building native extensions. This could take a while...
ERROR:  Error installing zebra-zpl:
	ERROR: Failed to build gem native extension.

    current directory: /home/user/.gem/ruby/gems/cups-0.1.10/ext
/usr/bin/ruby -r ./siteconf20180131-41796-vda998.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /home/user/.gem/ruby/gems/cups-0.1.10 for inspection.
Results logged to /home/user/.gem/ruby/extensions/x86_64-linux/cups-0.1.10/gem_make.out
----------------------------------------------------------------------------------------------------------

Error Bundle
---------------------------------------
$ bundle
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Using bundler 1.16.0
Fetching cups 0.1.10
Installing cups 0.1.10 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/user/.gem/ruby/gems/cups-0.1.10/ext
/usr/bin/ruby -r ./siteconf20180131-42078-w2pyzr.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /home/user/.gem/ruby/gems/cups-0.1.10 for inspection.
Results logged to /home/user/.gem/ruby/extensions/x86_64-linux/cups-0.1.10/gem_make.out

An error occurred while installing cups (0.1.10), and Bundler cannot continue.
Make sure that `gem install cups -v '0.1.10'` succeeds before bundling.

In Gemfile:
  zebra-zpl was resolved to 1.0.2, which depends on
    cups

**Comment by bbulpett** [comment]
You must have cups installed on host machine itself. For Centos you can follow this guide to install: [https://techpoli.info/2016/03/14/configure-cups-printing-server-on-centos/](https://techpoli.info/2016/03/14/configure-cups-printing-server-on-centos/)
