### ISSUE TITLE
Error While installing

### ISSUE THREAD

**Issue by saurabhmahajan-tudip** [bbulpett/zebra-zpl#23]
Tested on Ubuntu 16.04 and 14.04

Error gem install zebra-zpl
$ gem install zebra-zpl
Building native extensions. This could take a while...
ERROR: Error installing zebra-zpl:
ERROR: Failed to build gem native extension.

current directory: /home/user/.gem/ruby/gems/cups-0.1.10/ext
/usr/bin/ruby -r ./siteconf20180131-41796-vda998.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /home/user/.gem/ruby/gems/cups-0.1.10 for inspection.
Results logged to /home/user/.gem/ruby/extensions/x86_64-linux/cups-0.1.10/gem_make.out
Error Bundle
$ bundle
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Using bundler 1.16.0
Fetching cups 0.1.10
Installing cups 0.1.10 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory: /home/user/.gem/ruby/gems/cups-0.1.10/ext
/usr/bin/ruby -r ./siteconf20180131-42078-w2pyzr.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /home/user/.gem/ruby/gems/cups-0.1.10 for inspection.
Results logged to /home/user/.gem/ruby/extensions/x86_64-linux/cups-0.1.10/gem_make.out

An error occurred while installing cups (0.1.10), and Bundler cannot continue.
Make sure that gem install cups -v '0.1.10' succeeds before bundling.

In Gemfile:
zebra-zpl was resolved to 1.0.2, which depends on
cups

**Comment by jlgasparrini** [comment]
Did you try to install cups server?
`sudo apt install cups`

I have same gem version and I don't have any problems.

> cups (0.1.10)
> zebra-zpl (1.0.2)

I think that you have missing header files, try it https://stackoverflow.com/a/4502672/2853466

**Comment by saurabhmahajan-tudip** [comment]
This issue is resolved. Thanks
