### ISSUE TITLE
Convert PNG to ZPL

### ISSUE THREAD

**Issue by joevandyk** [bbulpett/zebra-zpl#34]
It would be nice to be able to convert a PNG to a ZPL file. We have labels currently in PNG format and would like to easily print those on Zebra printers.

**Comment by LagTag** [comment]
As a workaround, our team uses the [labelary](https://github.com/rjocoleman/labelary) gem to convert ZPL to PNG and back.

**Comment by mtking2** [comment]
I have created a very basic standalone gem, [img2zpl](https://github.com/mtking2/img2zpl), that does this. Right now (v0.1.2) it only converts an image into a `^GF` field and not an entire label (although it would be easy to implement support for that).

I'm also happy to help incorporate [img2zpl](https://github.com/mtking2/img2zpl) into [zebra-zpl](https://github.com/bbulpett/zebra-zpl) for this purpose.

**Comment by mtking2** [comment]
I have tested it out and my [img2zpl](https://github.com/mtking2/img2zpl) gem plays very nicely with [zebra-zpl](https://github.com/bbulpett/zebra-zpl):

```ruby
label = Zebra::Zpl::Label.new(
  width:        800,
  length:       1200,
  print_speed:  6
)

img = Img2Zpl::Image.open('label.png')
img.resize "#{label.width}x#{label.length}"
label << img

print_job.print label, host
```
It is likely we will incorporate [img2zpl](https://github.com/mtking2/img2zpl) into this gem in the future for a more native solution, but for now that should do the trick.
