### ISSUE TITLE
Release 1.1.0 on RubyGems

### ISSUE THREAD

**Issue by kwent** [bbulpett/zebra-zpl#38]
Time for a release ?

Regards

**Comment by mtking2** [comment]
It a bit late at this point but `1.0.5` is now released on RubyGems: https://rubygems.org/gems/zebra-zpl

I wouldn't consider version `1.1.0` quite ready yet. There are a few more things we'd like to include in that release. I've created a [milestone](https://github.com/bbulpett/zebra-zpl/milestone/1) to track the progress of that.

**Comment by oehlschl** [comment]
Awesome. Thanks for the quick turnaround @mtking2.
