### ISSUE TITLE
Memory Leak ?

### ISSUE THREAD

**Issue by kwent** [bbulpett/zebra-zpl#57]
Switch to 1.1.0 yesterday and seeing something which looks like a memory leak.

Back to `b8ef53714f907349c2c93ac1627af13082e23af8` sounds to stop the leak from happening.

<img width="1038" alt="Screen Shot 2019-11-04 at 6 58 53 PM" src="https://user-images.githubusercontent.com/879780/68230977-01703000-ffaf-11e9-8172-8168ee6c9106.png">

Any ideas?

**Comment by mtking2** [comment]
Here's the diff: https://github.com/bbulpett/zebra-zpl/compare/b8ef53714...master

I'm not seeing anything that would cause it.
