### ISSUE TITLE
I am not able to print PDF to 'Zebra  ZP 450-200 dpi' printer. I am not getting any error in my rescue block.

### ISSUE THREAD

**Issue by Nishi1** [bbulpett/zebra-zpl#65]
file_name = "#{Rails.root}/app/assets/images/fedex_"+tracking_id.to_s+".pdf"
file = open(file_name)
base_image = Base64.encode64(file.read)    
begin
  label = Zebra::Zpl::Label.new(
	  width:        200,
	  length:       200,
	  print_speed:  3
  )  
  pdf  = Zebra::Zpl::PDF417.new(
	  data:       base_image,
	  position:   [100, 100]
  )
  label<<pdf
  print_job = Zebra::PrintJob.new 'Zebra  ZP 450-200 dpi'
  ip = '127.0.0.1'         
  print_job.print label, ip, print_service: 'lp'     
  
rescue Exception=>e
  puts e.message      
end

**Comment by mtking2** [comment]
So the `Zebra::Zpl::PDF417` class is meant for generating [PDF417](https://en.wikipedia.org/wiki/PDF417) barcodes. What you're trying to do is the perfect use case for the `Zebra::Zpl::Image` class.

The image class can take an image, including PDFs, and convert it to ZPL to be applied to your label. I'm guessing you're trying to print a shipping label of some kind so in this case the image can be resized to the dimensions of the entire label:

```ruby
label = Zebra::Zpl::Label.new(
  width: 812,
  length: 1218,
  print_speed: 5
)

pdf = Zebra::Zpl::Image.new(
  path: "#{Rails.root}/app/assets/images/fedex_"+tracking_id.to_s+".pdf"
)

MiniMagick::Tool::Convert.new do |convert|
  convert << '-density' << '300'
  convert << pdf.src.path
  convert << '-resize' << "#{label.width}x#{label.length}"
  convert << pdf.src.path.ext('.jpg')
end

jpg = Zebra::Zpl::Image.new(
  path: pdf.src.path.ext('.jpg'),
  position: [0, 0]
)

label << jpg

# zpl = ''
# label.dump_contents zpl
# puts zpl.

print_job = Zebra::PrintJob.new 'Zebra ZP 450-200 dpi'
ip = 'localhost'
print_job.print label, ip, print_service: 'lp'
```

Here I convert the PDF to a JPG and resize to the label size of 812x1218 dots (standard size for a 4x6 in. shipping label @ 203 DPI). Let me know if that helps.

**Comment by Nishi1** [comment]
On line number 
pdf = Zebra::Zpl::Image.new(
  path: "#{Rails.root}/app/assets/images/fedex_"+tracking_id.to_s+".pdf"
)
Can i paas pdf file in Zebra::Zpl::Image.new(...) 
I am getting error:
`magick identify /tmp/mini_magick20200807-22784-4edg8f.pdf` failed with error:

**Comment by Nishi1** [comment]
While using commond **- print_job.print label, ip**
I am getting errors:
rlpr: error: connect to localhost:515: Connection refused
rlpr: fatal error: client_open(): cannot connect to lpd

Could you please help me to solve this problem?

**Comment by mtking2** [comment]
@Nishi1 I used `'localhost'` just as an example. It either needs to be the IP or hostname of the printer or the machine where the printer is. If the printer is actually on your local machine then either `'localhost'` or `'127.0.0.1'` should work.

What's the OS of the machine the printer is on? If it is Windows then you may need to enable the LPR and LPD services. [This section](https://github.com/bbulpett/zebra-zpl#printing-directly-to-windows-lpd) in the README explains how to do that.
