### ISSUE TITLE
Why is the maximum print speed 6?

### ISSUE THREAD

**Issue by eke-bb** [bbulpett/zebra-zpl#69]
According to this document: https://support.zebra.com/cpws/docs/zpl/PR_Command.pdf, it seems like the max should be 14. I would be happy to create a pull request unless there is some reason for the restriction to `6`.

**Comment by LagTag** [comment]
Yes go ahead and submit a PR for it.

This gem was pulled from a old EPL library that had hardcored some values,
so it may have been related to EPL limitations.
