### ISSUE TITLE
printing from web app to printer on osx

### ISSUE THREAD

**Issue by guersbru** [bbulpett/zebra-zpl#75]
I just setup a web app hosted on linux system. I connect the app with OSX client with a virtual zebra on localhost. When the print job is triggered, it fails :
- with `rlpr`
```
rlpr: fatal error: client_open(): cannot connect to lpd
rlpr: error: connect to localhost:515: Connection refused
rlpr: warning: cannot bind to privileged port: lpd may reject
```
- with `lp` nothing happens on the client, no failure on the server

When the app runs locally, `lp` printing completes successfully.
Am i missing something ?

**Comment by mtking2** [comment]
When sending the print command are you specifying the hostname/IP of the OSX client?

```ruby
ip = '123.4.5.6' 
# this should be the host/ip of the OSX machine.
# if calling from a rails controller you could use `request.remote_ip` here

print_job.print label, ip
```

**Comment by guersbru** [comment]
Thanks for your answer. I used remote_ip with no luck.
I left all print_job parameters open to try different configurations (https://bprinting.osc-fr1.scalingo.io/test_gem). 
I have tried on windows (with shared printer) with a virtual printer and physical one printer connected by USB. Same attempt on OSX (virtual and physical printer).
