### ISSUE TITLE
Code 37 Barcode options wrong.

### ISSUE THREAD

**Issue by rbrown** [bbulpett/zebra-zpl#76]
Hi, the parameters for some of the barcodes, particularly Code 37, do not match the sequence generated by Zebra::ZPL::Barcode.to_zpl. 

This is the default arguments in the code
`^B#{type}#{rotation},,#{human_readable}^FD#{data}`

But according to this [manual](https://www.zebra.com/content/dam/zebra/manuals/printers/common/programming/zpl-zbi2-pm-en.pdf) )(Page 55 ^B3) 
<img width="852" alt="Screenshot 2021-09-07 at 13 04 57" src="https://user-images.githubusercontent.com/233384/132341588-742caac3-55d1-4514-8ed3-87b63e713f25.png">
There are two arguments before `human_readable`. Which means that currently you can't turn human_readable off.

I'm willing to try and provide a patch if you can offer some guidance in how you'd like it structured? 

Thanks for the gem.

**Comment by DmytroVasin** [comment]
This Issue should be resolved by: https://github.com/bbulpett/zebra-zpl/pull/80

Please review.
